name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release (major, minor, patch)'
        required: true
        default: 'patch'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for git history

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Bump version and tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          ./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseType=${{ github.event.inputs.release_type }} --no-daemon -Dorg.gradle.console=plain
          git push origin main --follow-tags

      - name: Get version
        id: get_version
        run: echo "NEW_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.NEW_VERSION }}
          name: Release v${{ steps.get_version.outputs.NEW_VERSION }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}